apiVersion: v1
kind: Service
metadata:
  name: kc-simple-autos-lb
spec:
  type: LoadBalancer
  selector:
    app: kc-simple-autos
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
        name: http